import { useState } from 'react'
<<<<<<< HEAD
import Button from './ui/Button'
import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'

export default function ExportButton({ prompt, result }) {
=======

export default function ExportButton({ targetId = 'results-area', prompt }) {
>>>>>>> 133e016e0e0b1defff61fad3bd011d924aeb6602
  const [exporting, setExporting] = useState(false)

  async function handleExport() {
    setExporting(true)
    try {
<<<<<<< HEAD
      const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
      const pageW = pdf.internal.pageSize.getWidth()
      const pageH = pdf.internal.pageSize.getHeight()
      const primaryColor = [11, 102, 230]

      // Title Page / Overview Page
      pdf.setFontSize(18)
      pdf.setTextColor(...primaryColor)
      pdf.text('InsightFlow Professional Report', 20, 30)
      
      pdf.setFontSize(10)
      pdf.setTextColor(100, 116, 139)
      pdf.text(`Generated on: ${new Date().toLocaleString()}`, 20, 38)

      // Query Section
      pdf.setFontSize(12)
      pdf.setTextColor(15, 23, 42)
      pdf.setFont(undefined, 'bold')
      pdf.text('1. Business Query', 20, 55)
      pdf.setFontSize(11)
      pdf.setFont(undefined, 'normal')
      const queryLines = pdf.splitTextToSize(prompt || 'Dashboard Overview', pageW - 40)
      pdf.text(queryLines, 20, 65)

      let currentY = 65 + (queryLines.length * 6) + 15

      // Insight Section
      if (result && result.insight) {
        pdf.setFontSize(12)
        pdf.setFont(undefined, 'bold')
        pdf.text('2. Executive Insight', 20, currentY)
        pdf.setFontSize(11)
        pdf.setFont(undefined, 'normal')
        const insightLines = pdf.splitTextToSize(result.insight, pageW - 40)
        pdf.text(insightLines, 20, currentY + 10)
      }

      // Capture all Charts and put them on separate pages
      const chartElements = document.querySelectorAll('.chart-card')
      
      for (let i = 0; i < chartElements.length; i++) {
        pdf.addPage()
        
        // Page Header
        pdf.setFontSize(10)
        pdf.setTextColor(100, 116, 139)
        pdf.text(`InsightFlow Chart Visualization — ${i + 1}`, 15, 12)
        
        // Render Element using html-to-image
        const el = chartElements[i]
        const dataUrl = await toPng(el, {
          quality: 0.98,
          backgroundColor: '#ffffff',
          pixelRatio: 2,
        })
        
        const imgProps = pdf.getImageProperties(dataUrl)
        const usableH = pageH - 30
        const usableW = pageW - 30
        const ratio = Math.min(usableW / imgProps.width, usableH / imgProps.height)
        const imgW = imgProps.width * ratio
        const imgH = imgProps.height * ratio
        
        // Center the image horizontally & vertically below the header
        const xPos = (pageW - imgW) / 2
        const yPos = Math.max(20, (pageH - imgH) / 2)
        
        pdf.addImage(dataUrl, 'PNG', xPos, yPos, imgW, imgH)
        
        // Footer loop
        pdf.setFontSize(8)
        pdf.setTextColor(150, 150, 150)
        pdf.text('Generated by InsightFlow AI', 15, pageH - 10)
      }

      pdf.save(`insightflow-analysis-${Date.now()}.pdf`)
=======
      const { toPng } = await import('html-to-image')
      const { jsPDF } = await import('jspdf')

      const el = document.getElementById(targetId)
      if (!el) throw new Error('Results area not found')

      const dataUrl = await toPng(el, {
        quality: 0.96,
        backgroundColor: '#f5f6fa',
        pixelRatio: 2,
      })

      const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
      const pageW = pdf.internal.pageSize.getWidth()
      const pageH = pdf.internal.pageSize.getHeight()

      // Header
      pdf.setFontSize(10)
      pdf.setTextColor(100, 116, 139)
      pdf.text('InsightFlow Dashboard Export', 12, 10)
      pdf.text(new Date().toLocaleString(), pageW - 12, 10, { align: 'right' })
      if (prompt) {
        pdf.setFontSize(9)
        pdf.text(`Query: ${prompt.slice(0, 120)}`, 12, 16)
      }

      // Image
      const imgProps = pdf.getImageProperties(dataUrl)
      const usableH = pageH - 22
      const usableW = pageW - 24
      const ratio = Math.min(usableW / imgProps.width, usableH / imgProps.height)
      const imgW = imgProps.width * ratio
      const imgH = imgProps.height * ratio

      pdf.addImage(dataUrl, 'PNG', 12, 20, imgW, imgH)
      pdf.save(`insightflow-${Date.now()}.pdf`)
>>>>>>> 133e016e0e0b1defff61fad3bd011d924aeb6602
    } catch (err) {
      alert('Export failed: ' + err.message)
    } finally {
      setExporting(false)
    }
  }

  return (
<<<<<<< HEAD
    <Button variant="secondary" size="sm" onClick={handleExport} disabled={exporting}>
      {exporting ? '⏳ Generating PDF…' : '⬇ Export PDF Report'}
    </Button>
=======
    <button className="btn btn-secondary btn-sm" onClick={handleExport} disabled={exporting}>
      {exporting ? '⏳ Exporting…' : '⬇ Export PDF'}
    </button>
>>>>>>> 133e016e0e0b1defff61fad3bd011d924aeb6602
  )
}
