import { useState, useEffect, useRef } from 'react'
import { getSessionId } from '../utils/session'
import DynamicChart from './DynamicChart'
import { toPng } from 'html-to-image'
import { jsPDF } from 'jspdf'

export default function FullReportWidget({ onComplete, overview }) {
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const [exporting, setExporting] = useState(false)
  const hasTriggeredExport = useRef(false)

  // 1. Fetch data on mount
  useEffect(() => {
    async function fetchReport() {
      try {
        const res = await fetch('/api/auto-report', {
          method: 'POST',
          headers: { 'X-Session-ID': getSessionId() }
        })
        if (!res.ok) throw new Error('Failed to generate auto-report')
        const json = await res.json()
        setData(json)
      } catch (err) {
        setError(err.message)
      }
    }
    fetchReport()
  }, [])

  // 2. Automatically trigger export once data is ready
  useEffect(() => {
    let timer;
    if (data && !error && !exporting && !hasTriggeredExport.current) {
      hasTriggeredExport.current = true
      // Wait for React to render the invisible charts to the DOM
      timer = setTimeout(() => {
        handleExport()
      }, 1000)
    }
    return () => clearTimeout(timer)
  }, [data, error])

  async function handleExport() {
    setExporting(true)
    try {
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pageW = pdf.internal.pageSize.getWidth()
      const pageH = pdf.internal.pageSize.getHeight()
      const primaryColor = [26, 86, 219]

      // Cover Page
      pdf.setFontSize(22)
      pdf.setTextColor(...primaryColor)
      pdf.text('Comprehensive Business Insights Report', 20, 30)
      
      pdf.setFontSize(11)
      pdf.setTextColor(75, 85, 99)
      pdf.text(`Generated by InsightFlow AI on ${new Date().toLocaleDateString()}`, 20, 40)

      let currentY = 55;

      const drawTextWithPagination = (lines) => {
        lines.forEach(line => {
          if (currentY > pageH - 25) {
            pdf.addPage()
            currentY = 20
          }
          pdf.text(line, 20, currentY)
          currentY += 5
        })
      }

      // Executive Summary
      pdf.setFontSize(14)
      pdf.setTextColor(17, 24, 39)
      pdf.setFont(undefined, 'bold')
      pdf.text('Executive Summary', 20, currentY)
      currentY += 8;
      
      pdf.setFontSize(11)
      pdf.setTextColor(55, 65, 81)
      pdf.setFont(undefined, 'normal')
      const summaryLines = pdf.splitTextToSize(data.insight || 'No summary available.', pageW - 40)
      drawTextWithPagination(summaryLines)
      currentY += 8;

      // Dataset Overview
      if (overview?.summary) {
        if (currentY > pageH - 40) { pdf.addPage(); currentY = 20; }
        pdf.setFontSize(14)
        pdf.setTextColor(17, 24, 39)
        pdf.setFont(undefined, 'bold')
        pdf.text('Dataset Overview', 20, currentY)
        currentY += 8;

        pdf.setFontSize(11)
        pdf.setTextColor(55, 65, 81)
        pdf.setFont(undefined, 'normal')
        const overviewLines = pdf.splitTextToSize(overview.summary, pageW - 40)
        drawTextWithPagination(overviewLines)
        currentY += 8;
      }

      // KPIs
      if (data.kpis && data.kpis.length > 0) {
        if (currentY > pageH - 40) { pdf.addPage(); currentY = 20; }
        pdf.setFontSize(14)
        pdf.setTextColor(17, 24, 39)
        pdf.setFont(undefined, 'bold')
        pdf.text('Key Performance Indicators', 20, currentY)
        currentY += 8;
        
        pdf.setFontSize(11)
        pdf.setTextColor(55, 65, 81)
        pdf.setFont(undefined, 'normal')
        data.kpis.forEach(k => {
          const kLine = pdf.splitTextToSize(`• ${k.label}: ${k.value}`, pageW - 40)
          drawTextWithPagination(kLine)
        })
        currentY += 8;
      }

      // Charts Pages
      const chartElements = document.querySelectorAll('.report-chart-card')
      for (let i = 0; i < chartElements.length; i++) {
        pdf.addPage()
        
        const el = chartElements[i]
        const title = el.getAttribute('data-title') || `Insight ${i+1}`
        
        pdf.setFontSize(14)
        pdf.setTextColor(...primaryColor)
        pdf.setFont(undefined, 'bold')
        const titleLines = pdf.splitTextToSize(title, pageW - 40)
        pdf.text(titleLines, 20, 20)

        // Capture chart
        const dataUrl = await toPng(el, { backgroundColor: '#ffffff', pixelRatio: 2 })
        const imgProps = pdf.getImageProperties(dataUrl)
        
        // Fit to portrait page
        const maxWidth = pageW - 40
        const maxHeight = pageH - 50
        let ratio = maxWidth / imgProps.width
        if (imgProps.height * ratio > maxHeight) {
           ratio = maxHeight / imgProps.height
        }
        
        // place image below the title
        pdf.addImage(dataUrl, 'PNG', 20, 25 + (titleLines.length * 5), imgProps.width * ratio, imgProps.height * ratio)
      }

      pdf.save(`insightflow-full-report-${Date.now()}.pdf`)
      if (onComplete) onComplete()
    } catch (err) {
      console.error(err)
      alert('Report export failed: ' + err.message)
      if (onComplete) onComplete()
    }
  }

  // Error state
  if (error) {
    return (
      <div className="report-overlay" style={{ zIndex: 9999 }}>
        <div className="report-modal">
          <h3 style={{ color: 'var(--danger)', marginBottom: 16 }}>Report Generation Failed</h3>
          <p className="error-text">{error}</p>
          <button className="btn btn-secondary" onClick={onComplete}>Close</button>
        </div>
      </div>
    )
  }

  // Loading & Generating state
  return (
    <div className="report-overlay" style={{ zIndex: 9999 }}>
      
      {/* Loading Modal */}
      <div className="report-modal" style={{ maxWidth: 450, textAlign: 'center' }}>
        <div className="pipeline-progress">
          <div className="pipeline-label" style={{ fontSize: '1.2rem', marginBottom: 12 }}>
            {exporting || data ? 'Exporting PDF Report...' : 'Analyzing Dataset...'}
          </div>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>
            {!data 
              ? 'AI is identifying trends, distributions, and calculating KPIs across your entire dataset.' 
              : 'Generating high-resolution charts and compiling your business report.'}
          </p>
          <div className="loading-spinner" style={{ margin: '24px auto 10px', width: 40, height: 40, borderTopColor: 'var(--primary)' }}></div>
        </div>
      </div>

      {/* Invisible container for charts (required for html-to-image) */}
      {data && (
        <div style={{ position: 'absolute', top: -9999, left: -9999, opacity: 0, pointerEvents: 'none', width: '1000px' }}>
          <div className="report-charts-grid" style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            {data.charts?.map((chart, i) => (
              <div key={i} className="chart-card report-chart-card" data-title={chart.title} style={{ padding: 24, background: '#ffffff', width: '800px', height: '550px' }}>
                <h5 style={{ fontSize: '20px', marginBottom: 20, color: '#111827' }}>{chart.title}</h5>
                <div style={{ height: '450px' }}>
                  <DynamicChart 
                    type={chart.type} rows={chart.rows} 
                    xCol={chart.x_col} yCols={chart.y_cols} 
                    colorCol={chart.color_col} 
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

    </div>
  )
}
